/**
 * This file is autogenerated. Do not edit by hand — run `pnpm generate`.
 *
 * Non-local chain deployments live here; local (chainId 31337)
 * deployments live in `./ConfidentialNegotiation.local.ts` (gitignored) and are merged in
 * at module load. Import by name: `import { ConfidentialNegotiation } from "~~/contracts/ConfidentialNegotiation";`
 */
import { ConfidentialNegotiation as ConfidentialNegotiation_LOCAL } from "./ConfidentialNegotiation.local";
import type { ContractDeployment } from "~~/utils/contract";

const REMOTE = {
  11155111: {
    address: "0xfbdBA692809ab7ebf90Ca20069a6a42e078faB2c",
    abi: [
      {
        type: "function",
        name: "cancelSession",
        inputs: [
          {
            name: "sessionId",
            type: "uint256",
            internalType: "uint256",
          },
        ],
        outputs: [],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "confidentialProtocolId",
        inputs: [],
        outputs: [
          {
            name: "",
            type: "uint256",
            internalType: "uint256",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "createSession",
        inputs: [
          {
            name: "partyB",
            type: "address",
            internalType: "address",
          },
        ],
        outputs: [
          {
            name: "sessionId",
            type: "uint256",
            internalType: "uint256",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "getDealExists",
        inputs: [
          {
            name: "sessionId",
            type: "uint256",
            internalType: "uint256",
          },
        ],
        outputs: [
          {
            name: "",
            type: "bytes32",
            internalType: "ebool",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "getSession",
        inputs: [
          {
            name: "sessionId",
            type: "uint256",
            internalType: "uint256",
          },
        ],
        outputs: [
          {
            name: "partyA",
            type: "address",
            internalType: "address",
          },
          {
            name: "partyB",
            type: "address",
            internalType: "address",
          },
          {
            name: "ceilingSet",
            type: "bool",
            internalType: "bool",
          },
          {
            name: "floorSet",
            type: "bool",
            internalType: "bool",
          },
          {
            name: "revealed",
            type: "bool",
            internalType: "bool",
          },
          {
            name: "cancelled",
            type: "bool",
            internalType: "bool",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "getSuggestedValue",
        inputs: [
          {
            name: "sessionId",
            type: "uint256",
            internalType: "uint256",
          },
        ],
        outputs: [
          {
            name: "",
            type: "bytes32",
            internalType: "euint64",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "nextSessionId",
        inputs: [],
        outputs: [
          {
            name: "",
            type: "uint256",
            internalType: "uint256",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "reveal",
        inputs: [
          {
            name: "sessionId",
            type: "uint256",
            internalType: "uint256",
          },
        ],
        outputs: [],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "submitCeiling",
        inputs: [
          {
            name: "sessionId",
            type: "uint256",
            internalType: "uint256",
          },
          {
            name: "value",
            type: "bytes32",
            internalType: "externalEuint64",
          },
          {
            name: "inputProof",
            type: "bytes",
            internalType: "bytes",
          },
        ],
        outputs: [],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "submitFloor",
        inputs: [
          {
            name: "sessionId",
            type: "uint256",
            internalType: "uint256",
          },
          {
            name: "value",
            type: "bytes32",
            internalType: "externalEuint64",
          },
          {
            name: "inputProof",
            type: "bytes",
            internalType: "bytes",
          },
        ],
        outputs: [],
        stateMutability: "nonpayable",
      },
      {
        type: "event",
        name: "CeilingSubmitted",
        inputs: [
          {
            name: "sessionId",
            type: "uint256",
            indexed: true,
            internalType: "uint256",
          },
        ],
        anonymous: false,
      },
      {
        type: "event",
        name: "FloorSubmitted",
        inputs: [
          {
            name: "sessionId",
            type: "uint256",
            indexed: true,
            internalType: "uint256",
          },
        ],
        anonymous: false,
      },
      {
        type: "event",
        name: "Revealed",
        inputs: [
          {
            name: "sessionId",
            type: "uint256",
            indexed: true,
            internalType: "uint256",
          },
        ],
        anonymous: false,
      },
      {
        type: "event",
        name: "SessionCancelled",
        inputs: [
          {
            name: "sessionId",
            type: "uint256",
            indexed: true,
            internalType: "uint256",
          },
        ],
        anonymous: false,
      },
      {
        type: "event",
        name: "SessionCreated",
        inputs: [
          {
            name: "sessionId",
            type: "uint256",
            indexed: true,
            internalType: "uint256",
          },
          {
            name: "partyA",
            type: "address",
            indexed: true,
            internalType: "address",
          },
          {
            name: "partyB",
            type: "address",
            indexed: true,
            internalType: "address",
          },
        ],
        anonymous: false,
      },
      {
        type: "error",
        name: "AlreadyRevealed",
        inputs: [],
      },
      {
        type: "error",
        name: "AlreadySubmitted",
        inputs: [],
      },
      {
        type: "error",
        name: "NotAParty",
        inputs: [],
      },
      {
        type: "error",
        name: "NotReadyToReveal",
        inputs: [],
      },
      {
        type: "error",
        name: "SenderNotAllowedToUseHandle",
        inputs: [
          {
            name: "handle",
            type: "bytes32",
            internalType: "bytes32",
          },
          {
            name: "sender",
            type: "address",
            internalType: "address",
          },
        ],
      },
      {
        type: "error",
        name: "SessionIsCancelled",
        inputs: [],
      },
      {
        type: "error",
        name: "WrongParty",
        inputs: [],
      },
      {
        type: "error",
        name: "ZamaProtocolUnsupported",
        inputs: [],
      },
    ],
    deployedOnBlock: 11215114,
  },
} as const;

export const ConfidentialNegotiation = {
  ...REMOTE,
  ...ConfidentialNegotiation_LOCAL,
} as const satisfies Partial<Record<number, ContractDeployment>>;
