/**
 * This file is autogenerated. Do not edit by hand — run `pnpm generate`.
 *
 * Non-local chain deployments live here; local (chainId 31337)
 * deployments live in `./ConfidentialNegotiation.local.ts` (gitignored) and are merged in
 * at module load. Import by name: `import { ConfidentialNegotiation } from "~~/contracts/ConfidentialNegotiation";`
 */
import { ConfidentialNegotiation as ConfidentialNegotiation_LOCAL } from "./ConfidentialNegotiation.local";
import type { ContractDeployment } from "~~/utils/contract";

const REMOTE = {} as const;

export const ConfidentialNegotiation = {
  ...REMOTE,
  ...ConfidentialNegotiation_LOCAL,
} as const satisfies Partial<Record<number, ContractDeployment>>;
